# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_LinearRegression_create <- function() {
    .Call('_linearmodels_cpp_LinearRegression_create', PACKAGE = 'linearmodels')
}

cpp_LinearRegression_fit <- function(ptr, x, y) {
    invisible(.Call('_linearmodels_cpp_LinearRegression_fit', PACKAGE = 'linearmodels', ptr, x, y))
}

cpp_LinearRegression_predict <- function(ptr, x) {
    .Call('_linearmodels_cpp_LinearRegression_predict', PACKAGE = 'linearmodels', ptr, x)
}

cpp_LinearRegression_getCoef <- function(ptr) {
    .Call('_linearmodels_cpp_LinearRegression_getCoef', PACKAGE = 'linearmodels', ptr)
}

