# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_LinearRegression_create <- function() {
    .Call('_linearmodels_cpp_LinearRegression_create', PACKAGE = 'linearmodels')
}

cpp_LinearRegression_fit <- function(ptr, x, y) {
    invisible(.Call('_linearmodels_cpp_LinearRegression_fit', PACKAGE = 'linearmodels', ptr, x, y))
}

cpp_LinearRegression_predict <- function(ptr, x) {
    .Call('_linearmodels_cpp_LinearRegression_predict', PACKAGE = 'linearmodels', ptr, x)
}

cpp_LinearRegression_getCoef <- function(ptr) {
    .Call('_linearmodels_cpp_LinearRegression_getCoef', PACKAGE = 'linearmodels', ptr)
}

cpp_LinearRegression_setCoef <- function(ptr, coef) {
    invisible(.Call('_linearmodels_cpp_LinearRegression_setCoef', PACKAGE = 'linearmodels', ptr, coef))
}

cpp_LinearRegression_getFitted <- function(ptr) {
    .Call('_linearmodels_cpp_LinearRegression_getFitted', PACKAGE = 'linearmodels', ptr)
}

cpp_LinearRegression_setFitted <- function(ptr, x) {
    invisible(.Call('_linearmodels_cpp_LinearRegression_setFitted', PACKAGE = 'linearmodels', ptr, x))
}

cpp_RidgeRegression_create <- function(lambda) {
    .Call('_linearmodels_cpp_RidgeRegression_create', PACKAGE = 'linearmodels', lambda)
}

cpp_RidgeRegression_fit <- function(ptr, x, y) {
    invisible(.Call('_linearmodels_cpp_RidgeRegression_fit', PACKAGE = 'linearmodels', ptr, x, y))
}

cpp_RidgeRegression_predict <- function(ptr, x) {
    .Call('_linearmodels_cpp_RidgeRegression_predict', PACKAGE = 'linearmodels', ptr, x)
}

cpp_RidgeRegression_getCoef <- function(ptr) {
    .Call('_linearmodels_cpp_RidgeRegression_getCoef', PACKAGE = 'linearmodels', ptr)
}

cpp_RidgeRegression_setCoef <- function(ptr, coef) {
    invisible(.Call('_linearmodels_cpp_RidgeRegression_setCoef', PACKAGE = 'linearmodels', ptr, coef))
}

cpp_RidgeRegression_getFitted <- function(ptr) {
    .Call('_linearmodels_cpp_RidgeRegression_getFitted', PACKAGE = 'linearmodels', ptr)
}

cpp_RidgeRegression_setFitted <- function(ptr, x) {
    invisible(.Call('_linearmodels_cpp_RidgeRegression_setFitted', PACKAGE = 'linearmodels', ptr, x))
}

cpp_RidgeRegression_setLambda <- function(ptr, x) {
    invisible(.Call('_linearmodels_cpp_RidgeRegression_setLambda', PACKAGE = 'linearmodels', ptr, x))
}

